module(
    name = "example_error_flag_disabled",
    version = "0.0.0",
)

bazel_dep(name = "lib_a", version = "0.0.0")
local_path_override(
    module_name = "lib_a",
    path = "../lib_a",
)

# This should fail because --experimental_configurable_targets is not set.
override_target(
    target = "@lib_a//:content",
    replacement = "//:replacement",
)
