module(
    name = "lib_f",
    version = "0.0.0",
)

bazel_dep(name = "lib_a", version = "0.0.0")

# Extension marked as dev_dependency.
# Included when this module is root or dev deps are not suppressed.
extend_target(
    target = "@lib_a//:content",
    extra = "//:dev_content",
    dev_dependency = True,
)
