module(
    name = "example_extend_output_groups",
    version = "0.0.0",
)

bazel_dep(name = "lib_a", version = "0.0.0")
local_path_override(
    module_name = "lib_a",
    path = "../lib_a",
)

bazel_dep(name = "lib_e", version = "0.0.0")
local_path_override(
    module_name = "lib_e",
    path = "../lib_e",
)
